// routes/metaWebhookRoutes.js
// Production-Ready Meta WhatsApp Cloud API Webhook Handler (GET & POST /webhook)
const express = require('express');
const router = express.Router();
const WhatsAppMessage = require('../models/WhatsAppMessage');
const WhatsAppWebhookEvent = require('../models/WhatsAppWebhookEvent');

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. META WEBHOOK VERIFICATION (GET /webhook)
 * ─────────────────────────────────────────────────────────────────────────────
 * Meta sends a GET request to verify endpoint ownership when setting up the webhook.
 * Expected query parameters:
 *   - hub.mode: 'subscribe'
 *   - hub.verify_token: Token configured in Meta Developer Dashboard
 *   - hub.challenge: Random alphanumeric string generated by Meta
 *
 * Requirements:
 *   - If mode === 'subscribe' and hub.verify_token === META_VERIFY_TOKEN:
 *     Respond with HTTP 200 and exactly the hub.challenge string.
 *   - Otherwise:
 *     Respond with HTTP 403 Forbidden.
 */
async function handleWebhookVerification(req, res) {
  try {
    // Support both flat query params ('hub.mode') and parsed nested params (req.query.hub?.mode)
    let mode = req.query['hub.mode'] || req.query.hub?.mode;
    let token = req.query['hub.verify_token'] || req.query.hub?.verify_token;
    let challenge = req.query['hub.challenge'] || req.query.hub?.challenge;

    // Fallback: manually parse raw URL in case query string was encoded
    if (!mode || !token || !challenge) {
      try {
        const parsedUrl = new URL(req.originalUrl || req.url, 'http://localhost');
        mode = mode || parsedUrl.searchParams.get('hub.mode');
        token = token || parsedUrl.searchParams.get('hub.verify_token');
        challenge = challenge || parsedUrl.searchParams.get('hub.challenge');
      } catch {
        // ignore URL parse errors
      }
    }

    const expectedToken =
      process.env.META_VERIFY_TOKEN ||
      process.env.WHATSAPP_VERIFY_TOKEN ||
      'bovato_whatsapp_verify_token_2026';

    console.log(`🔍 [META WEBHOOK GET] Mode: "${mode}", Token provided: "${token ? '***' : 'NONE'}"`);

    // Verification check
    if (mode === 'subscribe' && token === expectedToken) {
      console.log('✅ [META WEBHOOK GET] Verification successful! Responding with challenge.');

      // Safely record verification event in audit log if model is available
      try {
        await WhatsAppWebhookEvent.create({
          eventType: 'verification',
          status: 'verified',
          rawPayload: { mode, challengeReceived: true },
        });
      } catch (logErr) {
        // Non-blocking
      }

      // Must return exactly hub.challenge with HTTP 200
      return res.status(200).send(challenge);
    } else {
      console.warn('❌ [META WEBHOOK GET] Verification failed: Token mismatch or invalid mode.');

      try {
        await WhatsAppWebhookEvent.create({
          eventType: 'verification',
          status: 'failed',
          rawPayload: { mode, tokenProvided: token },
          errorMessage: 'Token mismatch with META_VERIFY_TOKEN',
        });
      } catch (logErr) {
        // Non-blocking
      }

      return res.status(403).send('Forbidden: Verification token mismatch');
    }
  } catch (err) {
    console.error('❌ [META WEBHOOK GET ERROR]:', err.message);
    return res.status(500).send('Internal Server Error');
  }
}

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 2. META WEBHOOK EVENT RECEIVER (POST /webhook)
 * ─────────────────────────────────────────────────────────────────────────────
 * Meta sends real-time WhatsApp events (delivery receipts, read receipts, inbound messages).
 * Requirements:
 *   - Fast response: Always return HTTP 200 OK within 3-5 seconds to prevent Meta retries.
 *   - Safe processing: Log events, update message status if known, without modifying existing order/payment logic.
 */
async function handleWebhookEvents(req, res) {
  try {
    const body = req.body;

    // Check if event is from WhatsApp Business Account
    if (body && body.object === 'whatsapp_business_account') {
      const entries = body.entry || [];

      for (const entry of entries) {
        const changes = entry.changes || [];

        for (const change of changes) {
          const value = change.value;
          if (!value) continue;

          // A. Process Status Updates (sent, delivered, read, failed)
          const statuses = value.statuses || [];
          for (const s of statuses) {
            const wamid = s.id;
            const status = s.status; // 'sent' | 'delivered' | 'read' | 'failed'
            const timestamp = s.timestamp ? new Date(Number(s.timestamp) * 1000) : new Date();

            console.log(`📲 [META WEBHOOK STATUS] WAMID: ${wamid} -> ${String(status).toUpperCase()}`);

            // Update matching message in database if exists
            try {
              const updateData = { status };
              if (status === 'delivered') updateData.deliveredAt = timestamp;
              if (status === 'read') updateData.readAt = timestamp;
              if (status === 'failed') {
                updateData.failedAt = timestamp;
                const errDetail = s.errors?.[0];
                if (errDetail) {
                  updateData.errorMessage = `[${errDetail.code}] ${errDetail.title}: ${errDetail.message || ''}`;
                }
              }

              await WhatsAppMessage.updateOne({ providerMessageId: wamid }, { $set: updateData });
            } catch (updateErr) {
              console.warn('[META WEBHOOK] Failed to update message status:', updateErr.message);
            }

            // Audit log event
            try {
              await WhatsAppWebhookEvent.create({
                eventType: 'status_update',
                wamid,
                status,
                recipientPhone: s.recipient_id || '',
                rawPayload: s,
                processed: true,
              });
            } catch (logErr) {
              // Non-blocking
            }
          }

          // B. Log Inbound Customer Messages (read-only logging)
          const messages = value.messages || [];
          for (const m of messages) {
            const from = m.from;
            const messageType = m.type;
            const textBody = m.text?.body || `[${messageType} message]`;

            console.log(`💬 [META WEBHOOK INBOUND] From: +${from} | Text: "${textBody}"`);

            try {
              await WhatsAppWebhookEvent.create({
                eventType: 'incoming_message',
                wamid: m.id,
                senderPhone: from,
                messageBody: textBody,
                rawPayload: m,
                processed: true,
              });
            } catch (logErr) {
              // Non-blocking
            }
          }
        }
      }

      // Meta requires HTTP 200 acknowledgment
      return res.status(200).send('EVENT_RECEIVED');
    }

    // Acknowledge other events with 200 OK
    return res.status(200).send('OK');
  } catch (error) {
    console.error('❌ [META WEBHOOK POST ERROR]:', error.message);
    // Always return 200 to Meta so it does not disable the webhook URL
    return res.status(200).send('ERROR_LOGGED');
  }
}

// Support both root ('/') and explicit ('/webhook') paths
router.get('/', handleWebhookVerification);
router.get('/webhook', handleWebhookVerification);

router.post('/', handleWebhookEvents);
router.post('/webhook', handleWebhookEvents);

module.exports = router;
