// routes/metaWebhookRoutes.js
// Production-Ready Meta WhatsApp Cloud API Webhook Handler & Automation Engine (GET & POST /webhook)
const express = require('express');
const router = express.Router();
const WhatsAppMessage = require('../models/WhatsAppMessage');
const WhatsAppWebhookEvent = require('../models/WhatsAppWebhookEvent');
const WhatsAppSetting = require('../models/WhatsAppSetting');
const Lead = require('../models/Lead');
const AbandonedCart = require('../models/AbandonedCart');
const Order = require('../models/Order');

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. META WEBHOOK VERIFICATION (GET /webhook)
 * ─────────────────────────────────────────────────────────────────────────────
 * Meta sends a GET request to verify endpoint ownership when setting up the webhook.
 * Expected query parameters:
 *   - hub.mode: 'subscribe'
 *   - hub.verify_token: Token configured in Meta Developer Dashboard
 *   - hub.challenge: Random alphanumeric string generated by Meta
 */
async function handleWebhookVerification(req, res) {
  try {
    // Support both flat query params ('hub.mode') and parsed nested params (req.query.hub?.mode)
    let mode = req.query['hub.mode'] || req.query.hub?.mode;
    let token = req.query['hub.verify_token'] || req.query.hub?.verify_token;
    let challenge = req.query['hub.challenge'] || req.query.hub?.challenge;

    // Fallback: manually parse raw URL in case query string was encoded
    if (!mode || !token || !challenge) {
      try {
        const parsedUrl = new URL(req.originalUrl || req.url, 'http://localhost');
        mode = mode || parsedUrl.searchParams.get('hub.mode');
        token = token || parsedUrl.searchParams.get('hub.verify_token');
        challenge = challenge || parsedUrl.searchParams.get('hub.challenge');
      } catch {
        // ignore URL parse errors
      }
    }

    const validTokens = [
      process.env.META_VERIFY_TOKEN,
      process.env.WHATSAPP_VERIFY_TOKEN,
      process.env.WHATSAPP_ACCESS_TOKEN,
      'bovato_whatsapp_verify_token_2026',
    ].filter(Boolean);

    console.log(`🔍 [META WEBHOOK GET] Mode: "${mode}", Token: "${token ? token.slice(0, 8) + '...' : 'NONE'}"`);

    // Verification check: matches either the secret verify token OR the Meta access token the user entered
    const isTokenValid = validTokens.includes(token) || (token && process.env.WHATSAPP_ACCESS_TOKEN && token.startsWith(process.env.WHATSAPP_ACCESS_TOKEN.slice(0, 30)));

    if (mode === 'subscribe' && isTokenValid) {
      console.log('✅ [META WEBHOOK GET] Verification successful! Responding with challenge.');

      // Safely update WhatsAppSetting verified timestamp
      try {
        await WhatsAppSetting.updateOne(
          {},
          {
            $set: {
              webhookVerifiedAt: new Date(),
              webhookUrl: process.env.WHATSAPP_WEBHOOK_URL || 'http://localhost:5001/webhook',
            },
          }
        );
      } catch (dbErr) {
        // Non-blocking
      }

      // Safely record verification event in audit log
      try {
        await WhatsAppWebhookEvent.create({
          eventType: 'verification',
          status: 'verified',
          rawPayload: { mode, challengeReceived: true },
        });
      } catch (logErr) {
        // Non-blocking
      }

      // Must return exactly hub.challenge with HTTP 200
      return res.status(200).send(challenge);
    } else {
      console.warn('❌ [META WEBHOOK GET] Verification failed: Token mismatch or invalid mode.');

      try {
        await WhatsAppWebhookEvent.create({
          eventType: 'verification',
          status: 'failed',
          rawPayload: { mode, tokenProvided: token },
          errorMessage: 'Token mismatch with META_VERIFY_TOKEN',
        });
      } catch (logErr) {
        // Non-blocking
      }

      return res.status(403).send('Forbidden: Verification token mismatch');
    }
  } catch (err) {
    console.error('❌ [META WEBHOOK GET ERROR]:', err.message);
    return res.status(500).send('Internal Server Error');
  }
}

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 2. META WEBHOOK EVENT RECEIVER & AUTOMATION (POST /webhook)
 * ─────────────────────────────────────────────────────────────────────────────
 * Meta sends real-time WhatsApp events:
 *   A. Status Updates: sent, delivered, read, failed (syncs messages, orders & carts)
 *   B. Inbound Messages: customer replies (syncs opt-outs, CRM leads & order notes)
 */
async function handleWebhookEvents(req, res) {
  try {
    const body = req.body;

    if (body && body.object === 'whatsapp_business_account') {
      const entries = body.entry || [];

      for (const entry of entries) {
        const changes = entry.changes || [];

        for (const change of changes) {
          const value = change.value;
          if (!value) continue;

          // ── A. Process Message Status Updates (sent, delivered, read, failed) ────
          const statuses = value.statuses || [];
          for (const s of statuses) {
            const wamid = s.id;
            const status = s.status; // 'sent' | 'delivered' | 'read' | 'failed'
            const timestamp = s.timestamp ? new Date(Number(s.timestamp) * 1000) : new Date();

            console.log(`📲 [WHATSAPP AUTOMATION] WAMID: ${wamid} -> ${String(status).toUpperCase()}`);

            // 1. Audit log event
            try {
              await WhatsAppWebhookEvent.create({
                eventType: 'status_update',
                wamid,
                status,
                recipientPhone: s.recipient_id || '',
                rawPayload: s,
                processed: true,
              });
            } catch (logErr) {
              // Non-blocking
            }

            // 2. Update matching WhatsAppMessage record
            try {
              const message = await WhatsAppMessage.findOne({ providerMessageId: wamid });
              if (message) {
                message.status = status;
                if (status === 'sent' && !message.sentAt) message.sentAt = timestamp;
                if (status === 'delivered') message.deliveredAt = timestamp;
                if (status === 'read') message.readAt = timestamp;
                if (status === 'failed') {
                  message.failedAt = timestamp;
                  const errDetail = s.errors?.[0];
                  if (errDetail) {
                    message.errorMessage = `[${errDetail.code}] ${errDetail.title}: ${errDetail.message || ''}`;
                  }
                }
                await message.save();

                // 3. Automation: Update parent Lead status if linked
                if (message.leadId) {
                  await Lead.findByIdAndUpdate(message.leadId, { whatsappStatus: status });
                }

                // 4. Automation: Update AbandonedCart recovery status if linked
                if (message.cartId) {
                  const cart = await AbandonedCart.findById(message.cartId);
                  if (cart) {
                    if (status === 'delivered') cart.recoveryStatus = 'delivered';
                    else if (status === 'read') cart.recoveryStatus = 'read';
                    else if (status === 'failed') cart.recoveryStatus = 'failed';

                    cart.activityHistory.push({
                      event: `whatsapp_${status}`,
                      timestamp,
                      details: `WhatsApp delivery updated to ${status.toUpperCase()} (WAMID: ${wamid})`,
                    });
                    await cart.save();
                  }
                }
              }
            } catch (updateErr) {
              console.warn('[WHATSAPP AUTOMATION] Message status update notice:', updateErr.message);
            }
          }

          // ── B. Process Inbound Messages (Customer replies) ────────────────────────
          const incomingMessages = value.messages || [];
          for (const msg of incomingMessages) {
            const from = msg.from; // e.g. "919876543210"
            const textBody = msg.text?.body || `[${msg.type || 'message'}]`;
            const normalizedFrom = `+${from}`;

            console.log(`💬 [WHATSAPP INBOUND] From ${normalizedFrom}: "${textBody}"`);

            // 1. Audit log incoming message
            try {
              await WhatsAppWebhookEvent.create({
                eventType: 'incoming_message',
                wamid: msg.id || '',
                senderPhone: normalizedFrom,
                messageBody: textBody,
                rawPayload: msg,
                processed: true,
              });
            } catch (logErr) {
              // Non-blocking
            }

            // 2. Automation: Smart Opt-out Detection
            const isOptOut = /^(stop|unsubscribe|cancel|optout|halt)\b/i.test(textBody.trim());

            // 3. Automation: Update matching Abandoned Carts
            try {
              const carts = await AbandonedCart.find({
                $or: [
                  { phone: from },
                  { normalizedPhone: normalizedFrom },
                  { phone: normalizedFrom },
                ],
              });

              for (const c of carts) {
                if (isOptOut) {
                  c.optedOut = true;
                  c.optedOutAt = new Date();
                  c.recoveryStatus = 'opted_out';
                  c.activityHistory.push({
                    event: 'customer_opted_out',
                    timestamp: new Date(),
                    details: `Customer requested opt-out via WhatsApp: "${textBody}"`,
                  });
                }
                c.notes.push({
                  text: `💬 Customer replied on WhatsApp: "${textBody}"`,
                  author: 'Customer',
                  createdAt: new Date(),
                });
                await c.save();
              }
            } catch (cartErr) {
              console.warn('[WHATSAPP AUTOMATION] Cart sync notice:', cartErr.message);
            }

            // 4. Automation: Update matching CRM Leads
            try {
              const lead = await Lead.findOne({
                $or: [
                  { phone: from },
                  { normalizedPhone: normalizedFrom },
                  { phone: normalizedFrom },
                ],
              });

              if (lead) {
                lead.status = 'contacted';
                lead.lastContactedAt = new Date();
                lead.notes.push({
                  text: `💬 Customer replied on WhatsApp: "${textBody}"`,
                  author: 'Customer',
                  createdAt: new Date(),
                });
                await lead.save();
              }
            } catch (leadErr) {
              console.warn('[WHATSAPP AUTOMATION] Lead sync notice:', leadErr.message);
            }

            // 5. Automation: Link Customer Reply to Latest Order
            try {
              const cleanDigits = from.replace(/^91/, '');
              const order = await Order.findOne({
                $or: [
                  { 'shippingAddress.phone': from },
                  { 'shippingAddress.phone': cleanDigits },
                  { 'shippingAddress.phone': normalizedFrom },
                  { 'contactInfo.phone': from },
                  { 'contactInfo.phone': cleanDigits },
                ],
              }).sort({ createdAt: -1 });

              if (order && typeof order.addTrackingEvent === 'function') {
                order.addTrackingEvent({
                  timestamp: new Date(),
                  status: order.shippingStatus || 'IN_PROGRESS',
                  description: `WhatsApp Customer Reply: "${textBody}"`,
                  location: '',
                });
                await order.save();
              }
            } catch (orderErr) {
              console.warn('[WHATSAPP AUTOMATION] Order reply link notice:', orderErr.message);
            }
          }
        }
      }

      // Meta requires HTTP 200 acknowledgment within 3-5 seconds
      return res.status(200).send('EVENT_RECEIVED');
    }

    return res.status(200).send('OK');
  } catch (error) {
    console.error('❌ [META WEBHOOK POST ERROR]:', error.message);
    // Always return 200 to Meta so it does not disable the webhook URL
    return res.status(200).send('ERROR_LOGGED');
  }
}

// Support both root ('/') and explicit ('/webhook') paths
router.get('/', handleWebhookVerification);
router.get('/webhook', handleWebhookVerification);

router.post('/', handleWebhookEvents);
router.post('/webhook', handleWebhookEvents);

module.exports = router;
